export const accessoryStrings = {
  zh: {
    'accessory.compat': '兼容',
    'accessory.assumption': '尺寸与安装参数为设计假设 · 承载能力待实物验证',
    'accessory.stage.choose': '选择组件 → 点击可安装位置，即可安装',
    'accessory.stage.preview': '点击有效位置即可安装。',
    'accessory.hint.gym_rings': '使用既有吊环：点击水平管的安装位，检查吊点与下方空间。',
    'accessory.mount.frame': '点击符合 {size} 尺寸的完整方框安装位即可安装，也可依次点击两根对边管。',
    'accessory.mount.opposite-screws': '点击完整方框安装位即可安装，也可依次点击两条连续对边。对边各用两枚透明螺丝固定。',
    'accessory.mount.vertical-frame': '点击尺寸相符的竖直完整方框安装位即可安装，也可依次点击两根对边管。',
    'accessory.mount.horizontal-frame': '点击尺寸相符的水平完整方框安装位即可安装。需要四边支撑齐全，下方留有空间。',
    'accessory.mount.net-frame': '点击完整框格的安装位即可安装，绳网沿四边多点固定。',
    'accessory.mount.curved-frame': '点击两根平行四分之一弧管之间的安装位即可安装，布面或绳网沿弧管固定。',
    'accessory.mount.rails': '点击两根平行直管之间的安装位即可安装，布片套管边或桥面横杠固定在原管上。',
    'accessory.mount.tube': '点击原管上的可安装位置即可安装。',
    'accessory.hint.roller': '点击原直管上的安装位即可套上软体滚筒，两端需避开接头。',
    'accessory.mount.rope': '依次点击两根承载管上的固定位置，第二次点击即可连接绳子。按 Esc 可取消第一个端点。',
    'accessory.mount.corner': '点击由弧管与直管围成的完整扇形开口安装位即可安装。',
    'accessory.preview': '安装提示',
    'accessory.fixingEdges': '螺丝固定边',
    'accessory.fixing.vertical': '左右固定',
    'accessory.fixing.horizontal': '上下固定',
    'accessory.fixedColor': '固定配色：{color}',
    'accessory.mounts': '{n} 个固定点',
    'accessory.mountOne': '1 个固定点',
    'accessory.confirm': '确认安装',
    'accessory.cancel': '取消安装',
    'accessory.flip': '翻转方向盘朝向',
    'accessory.succeeded': '安装完成',
    'accessory.notes': '套装说明',
    'safety.accessory_mounts': '{n} 件配件的固定点或安装参数不完整。检查全部承载管与固定点。',
    'safety.accessory_support': '{n} 件配件的承载结构没有连通到地面。补齐支撑或移到落地结构上。',
    'safety.accessory_clearance': '{n} 件配件的空间与其他部件重叠。调整安装位置，并留出秋千活动空间。',
    'safety.accessory_load': '新增组件的尺寸与安装参数为设计假设，承载能力待实物验证。运动范围检查仅用于设计预览。',
    'accessory.hint.steering_wheel': '点击水平直管上的安装位即可安装。选中方向盘可翻转朝向。',
    'accessory.hint.swing': '点击水平直管上的安装位即可安装，需留出前后摆动空间。',
    'accessory.hint.panel_40x40_busy': '点击竖直 40×40 完整方框安装位即可安装，也可依次点击两根对边管。不可站立。',
    'accessory.hint.panel_40x40_pocket': '点击水平 40×40 完整方框安装位即可安装，也可依次点击两根对边管。不可站立。',
    'accessory.hint.trampoline': '点击水平完整框架安装位即可安装。支持 40×40、40×80、80×40 和 80×80 cm，沿四边多点固定。',
    'accessory.qdf.omitted': '已导出 QDF。未包含：{parts}。请用原生 JSON 保存完整配件。',
    'accessory.qdf.simplified': '已导出 QDF。{parts}为简化表示，未包含完整外观与安装关系。请用原生 JSON 保存。',
    'accessory.qdf.both': '已导出 QDF。未包含：{omitted}；简化表示：{simplified}。请用原生 JSON 保存完整组件。',
  },
  en: {
    'accessory.compat': 'Compatible',
    'accessory.assumption': 'Dimensions and mounting parameters are design assumptions · Load capacity unverified',
    'accessory.stage.choose': 'Choose a component → Click a suitable position to install',
    'accessory.stage.preview': 'Click a valid position to install.',
    'accessory.hint.gym_rings': 'Use the existing gym rings: click a mount on a horizontal tube and check the hangers and clearance below.',
    'accessory.mount.frame': 'Click a mount in a complete {size} frame to install, or click two opposite tubes in order.',
    'accessory.mount.opposite-screws': 'Click a mount in a complete frame to install, or select its two continuous opposite edges in order. Two clear screws secure each edge.',
    'accessory.mount.vertical-frame': 'Click a mount in a complete vertical frame of the matching size to install, or click two opposite tubes in order.',
    'accessory.mount.horizontal-frame': 'Click a mount in a complete horizontal frame of the matching size to install. All four edges need support and clearance below.',
    'accessory.mount.net-frame': 'Click a mount in a complete frame to install the net with multiple fixings along all four edges.',
    'accessory.mount.curved-frame': 'Click a mount between two parallel quarter-circle tubes to install the cloth or net along the curves.',
    'accessory.mount.rails': 'Click a mount between two parallel straight tubes to install the fabric sleeves or bridge bars on the original rails.',
    'accessory.mount.tube': 'Click a suitable position on an original tube to install.',
    'accessory.hint.roller': 'Click a mount on an original straight tube to fit the padded roller. Leave both end connectors clear.',
    'accessory.mount.rope': 'Click a fixing position on each of two support tubes. The second click connects the rope. Press Esc to cancel the first endpoint.',
    'accessory.mount.corner': 'Click a mount in a complete quarter-circle opening formed by curved and straight tubes to install.',
    'accessory.preview': 'Installation guide',
    'accessory.fixingEdges': 'Screw fixing edges',
    'accessory.fixing.vertical': 'Left / right',
    'accessory.fixing.horizontal': 'Top / bottom',
    'accessory.fixedColor': 'Fixed colour: {color}',
    'accessory.mounts': '{n} fixing points',
    'accessory.mountOne': '1 fixing point',
    'accessory.confirm': 'Confirm installation',
    'accessory.cancel': 'Cancel installation',
    'accessory.flip': 'Flip steering wheel facing',
    'accessory.succeeded': 'Installed',
    'accessory.notes': 'Kit notes',
    'safety.accessory_mounts': '{n} accessories have incomplete fixing points or installation parameters. Check every support tube and fixing point.',
    'safety.accessory_support': 'The support structures of {n} accessories do not connect to the ground. Complete the supports or move them to a grounded frame.',
    'safety.accessory_clearance': '{n} accessories overlap other parts. Adjust their positions and leave room for the swing to move.',
    'safety.accessory_load': 'Dimensions and mounting parameters of new components are design assumptions. Load capacity requires physical testing. Motion clearance checks are for design previews only.',
    'accessory.hint.steering_wheel': 'Click a mount on a horizontal straight tube to install. Select the wheel to flip its facing.',
    'accessory.hint.swing': 'Click a mount on a horizontal straight tube to install. Leave room to swing forwards and backwards.',
    'accessory.hint.panel_40x40_busy': 'Click a mount in a complete vertical 40×40 frame to install, or click two opposite tubes in order. Not a standing platform.',
    'accessory.hint.panel_40x40_pocket': 'Click a mount in a complete horizontal 40×40 frame to install, or click two opposite tubes in order. Not a standing platform.',
    'accessory.hint.trampoline': 'Click a mount in a complete horizontal frame to install. Supports 40×40, 40×80, 80×40 and 80×80 cm with multiple fixings on all four edges.',
    'accessory.qdf.omitted': 'QDF exported. Omitted: {parts}. Save native JSON to keep complete accessories.',
    'accessory.qdf.simplified': 'QDF exported. {parts} use simplified representations without their complete appearance or installation references. Save native JSON to keep them.',
    'accessory.qdf.both': 'QDF exported. Omitted: {omitted}; simplified representations: {simplified}. Save native JSON to keep complete components.',
  },
  de: {
    'accessory.compat': 'Kompatibel',
    'accessory.assumption': 'Maße und Montageparameter sind Entwurfsannahmen · Tragfähigkeit ungeprüft',
    'accessory.stage.choose': 'Bauteil wählen → Passende Position zum Montieren anklicken',
    'accessory.stage.preview': 'Gültige Position zum Montieren anklicken.',
    'accessory.hint.gym_rings': 'Vorhandene Turnringe verwenden: Montagestelle am waagerechten Rohr anklicken und Aufhängungen sowie Freiraum darunter prüfen.',
    'accessory.mount.frame': 'Montagestelle in einem vollständigen {size}-Rahmen zum Montieren anklicken oder nacheinander zwei gegenüberliegende Rohre wählen.',
    'accessory.mount.opposite-screws': 'Montagestelle im vollständigen Rahmen zum Montieren anklicken oder nacheinander zwei durchgehende gegenüberliegende Seiten wählen. Je zwei transparente Schrauben befestigen jede Seite.',
    'accessory.mount.vertical-frame': 'Montagestelle im vollständigen senkrechten Rahmen passender Größe zum Montieren anklicken oder nacheinander zwei gegenüberliegende Rohre wählen.',
    'accessory.mount.horizontal-frame': 'Montagestelle im vollständigen waagerechten Rahmen passender Größe zum Montieren anklicken. Alle vier Seiten müssen abgestützt und der Raum darunter frei sein.',
    'accessory.mount.net-frame': 'Montagestelle im vollständigen Rahmen zum Montieren anklicken. Das Netz wird an allen vier Seiten mehrfach befestigt.',
    'accessory.mount.curved-frame': 'Montagestelle zwischen zwei parallelen Viertelkreisrohren zum Montieren anklicken. Tuch oder Netz folgt den Bögen.',
    'accessory.mount.rails': 'Montagestelle zwischen zwei parallelen geraden Rohren zum Montieren anklicken. Stoffhülsen oder Brückenstäbe nutzen die Originalrohre.',
    'accessory.mount.tube': 'Passende Montagestelle an einem Originalrohr zum Montieren anklicken.',
    'accessory.hint.roller': 'Montagestelle am geraden Originalrohr anklicken, um die Polsterrolle anzubringen. Beide Endverbinder freihalten.',
    'accessory.mount.rope': 'Je eine Befestigungsposition an zwei Trägerrohren anklicken. Der zweite Klick verbindet das Seil. Esc verwirft den ersten Endpunkt.',
    'accessory.mount.corner': 'Montagestelle in einer vollständigen Viertelkreisöffnung aus Bogen- und geraden Rohren zum Montieren anklicken.',
    'accessory.preview': 'Montagehilfe',
    'accessory.fixingEdges': 'Schraubenkanten',
    'accessory.fixing.vertical': 'Links / rechts',
    'accessory.fixing.horizontal': 'Oben / unten',
    'accessory.fixedColor': 'Feste Farbe: {color}',
    'accessory.mounts': '{n} Befestigungspunkte',
    'accessory.mountOne': '1 Befestigungspunkt',
    'accessory.confirm': 'Montage bestätigen',
    'accessory.cancel': 'Montage abbrechen',
    'accessory.flip': 'Lenkradausrichtung umkehren',
    'accessory.succeeded': 'Montiert',
    'accessory.notes': 'Set-Hinweise',
    'safety.accessory_mounts': 'Bei {n} Zubehörteilen sind Befestigungspunkte oder Montageparameter unvollständig. Alle Trägerrohre und Befestigungspunkte prüfen.',
    'safety.accessory_support': 'Die Tragstrukturen von {n} Zubehörteilen sind nicht mit dem Boden verbunden. Die Stützen vervollständigen oder einen bodengestützten Rahmen verwenden.',
    'safety.accessory_clearance': '{n} Zubehörteile überschneiden sich mit anderen Teilen. Die Montageposition ändern und Bewegungsraum für die Schaukel lassen.',
    'safety.accessory_load': 'Maße und Montageparameter neuer Bauteile sind Entwurfsannahmen. Die Tragfähigkeit muss am realen Bauteil geprüft werden. Bewegungsprüfungen dienen nur der Entwurfsvorschau.',
    'accessory.hint.steering_wheel': 'Montagestelle am waagerechten geraden Rohr zum Montieren anklicken. Das Lenkrad auswählen, um die Ausrichtung umzukehren.',
    'accessory.hint.swing': 'Montagestelle am waagerechten geraden Rohr zum Montieren anklicken. Platz zum Schwingen nach vorn und hinten lassen.',
    'accessory.hint.panel_40x40_busy': 'Montagestelle im vollständigen senkrechten 40×40-Rahmen zum Montieren anklicken oder zwei gegenüberliegende Rohre wählen. Keine Standfläche.',
    'accessory.hint.panel_40x40_pocket': 'Montagestelle im vollständigen waagerechten 40×40-Rahmen zum Montieren anklicken oder zwei gegenüberliegende Rohre wählen. Keine Standfläche.',
    'accessory.hint.trampoline': 'Montagestelle im vollständigen waagerechten Rahmen zum Montieren anklicken. Unterstützt 40×40, 40×80, 80×40 und 80×80 cm mit mehreren Befestigungen an allen vier Seiten.',
    'accessory.qdf.omitted': 'QDF exportiert. Nicht enthalten: {parts}. Natives JSON speichert das vollständige Zubehör.',
    'accessory.qdf.simplified': 'QDF exportiert. {parts} werden vereinfacht dargestellt, ohne vollständige Form und Montagebezüge. Bitte als natives JSON speichern.',
    'accessory.qdf.both': 'QDF exportiert. Nicht enthalten: {omitted}; vereinfacht dargestellt: {simplified}. Natives JSON speichert vollständige Komponenten.',
  },
}
