export const builderChromeStrings = {
  zh: {
    'tool.undo': '撤销', 'tool.redo': '重做', 'chrome.tools': '造型工具',
    'chrome.navigation': 'Builder 菜单', 'chrome.close': '关闭面板', 'chrome.closeTab': '关闭设计',
    'chrome.start': '开始与保存', 'chrome.export': '导出与分享', 'chrome.language': '界面语言',
    'chrome.image': '模型图片', 'chrome.backup': '本地备份', 'chrome.original': '原厂文件', 'chrome.manual': '拼装说明书',
    'chrome.imageHint': 'PNG · 展示造型', 'chrome.backupHint': 'JSON · 保留设计',
    'chrome.originalHint': 'QDF · 原厂软件打开', 'chrome.manualHint': 'PDF · 逐步搭建',
    'chrome.save': '保存', 'chrome.saveAs': '另存为',
    'chrome.saveShortcut': '{save}', 'chrome.saveAsShortcut': '{saveAs}',
    'chrome.expand': '展开面板', 'chrome.compact': '收起面板',
  },
  en: {
    'tool.undo': 'Undo', 'tool.redo': 'Redo', 'chrome.tools': 'Modeling tools',
    'chrome.navigation': 'Builder menus', 'chrome.close': 'Close panel', 'chrome.closeTab': 'Close design',
    'chrome.start': 'Create & save', 'chrome.export': 'Export & share', 'chrome.language': 'Interface language',
    'chrome.image': 'Model image', 'chrome.backup': 'Local backup', 'chrome.original': 'Original file', 'chrome.manual': 'Assembly guide',
    'chrome.imageHint': 'PNG · Show your model', 'chrome.backupHint': 'JSON · Keep your design',
    'chrome.originalHint': 'QDF · Open in official software', 'chrome.manualHint': 'PDF · Build step by step',
    'chrome.save': 'Save', 'chrome.saveAs': 'Save as',
    'chrome.saveShortcut': '{save}', 'chrome.saveAsShortcut': '{saveAs}',
    'chrome.expand': 'Expand panel', 'chrome.compact': 'Collapse panel',
  },
  de: {
    'tool.undo': 'Zurück', 'tool.redo': 'Vorwärts', 'chrome.tools': 'Modellwerkzeuge',
    'chrome.navigation': 'Builder-Menüs', 'chrome.close': 'Panel schließen', 'chrome.closeTab': 'Entwurf schließen',
    'chrome.start': 'Erstellen & speichern', 'chrome.export': 'Exportieren & teilen', 'chrome.language': 'Sprache der Oberfläche',
    'chrome.image': 'Modellbild', 'chrome.backup': 'Lokale Sicherung', 'chrome.original': 'Originaldatei', 'chrome.manual': 'Aufbauanleitung',
    'chrome.imageHint': 'PNG · Modell zeigen', 'chrome.backupHint': 'JSON · Entwurf sichern',
    'chrome.originalHint': 'QDF · In Originalsoftware öffnen', 'chrome.manualHint': 'PDF · Schrittweise aufbauen',
    'chrome.save': 'Speichern', 'chrome.saveAs': 'Speichern unter',
    'chrome.saveShortcut': '{save}', 'chrome.saveAsShortcut': '{saveAs}',
    'chrome.expand': 'Panel erweitern', 'chrome.compact': 'Panel verkleinern',
  },
}
