import {readFileSync} from 'node:fs';
import {beforeAll,describe,it,expect} from 'vitest';
import {loadCatalog} from './catalog.js';
import {BuildModel} from './model.js';
import {computeAssemblyPlan,assemblyDetailState,assemblyState} from './assemblyPlan.js';
import {nativeAccessorySupport} from './assemblyAccessoryMethods.js';
import {createCoreChannels} from './assemblyCoreChannels.js';
import {scheduleAssemblyAccessories,addAssemblyOperations} from './assemblyOperations.js';
beforeAll(async()=>{await loadCatalog();});
const square=()=>{const m=new BuildModel(),n=[[0,0,0],[40,0,0],[40,0,40],[0,0,40]].map(p=>m.addNode(...p));const tubes=n.map((a,i)=>m.addTube(a.id,n[(i+1)%4].id,'T35','blue',35)!);return {m,n,tubes};};
const stepsFor=(m:any):any[]=>[...m.tubes.values()].map((t:any,i:number)=>({id:`step-${i}`,regionId:'body',partIds:[t.id],tubeIds:[t.id],nodeIds:[],panelIds:[],textileIds:[],fittingIds:[],slideIds:[],clampIds:[],dependsOn:[],action:{type:'build',detached:false}}));
describe('persisted assembly region compatibility',()=>{
  it('preserves actual frame kinds and interfaces after moved accessories are saved in region ownership',()=>{
    const m=new BuildModel();m.loadJSON(JSON.parse(readFileSync('public/assembly-fixtures/s33.json','utf8')));
    const original=computeAssemblyPlan(m),config={version:1,regions:original.regions.map((region:any)=>({id:region.id,name:region.name,partIds:[...region.partIds]})),order:original.regions.map((region:any)=>region.id)},restored=computeAssemblyPlan(m,config);
    const physicalKinds=(plan:any)=>plan.regions.map((region:any)=>[region.id,region.kind,region.supportRegionId||null]).sort((a:any,b:any)=>a[0].localeCompare(b[0]));
    expect(physicalKinds(restored)).toEqual(physicalKinds(original));
    const interfaces=(plan:any)=>plan.interfaces.map((port:any)=>[port.sourceRegionId,port.targetRegionId,port.nodeId]).sort((a:any,b:any)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));
    expect(interfaces(restored)).toEqual(interfaces(original));
    for(const plan of [original,restored]){
      expect(plan.interfaces.filter((port:any)=>port.attachment==='prethread-ring').map((port:any)=>port.clampId).sort()).toEqual(['k52','k53']);
      expect(plan.interfaces.filter((port:any)=>port.attachment==='upper-frame')).toHaveLength(6);
      expect(plan.canExport).toBe(false);
      for(const clampId of ['k52','k53'])expect(plan.diagnostics.some((d:any)=>d.code==='PRETHREAD_METHOD_UNVERIFIED'&&d.partIds.includes(clampId))).toBe(true);
      expect(plan.steps.flatMap((step:any)=>step.operations).every((operation:any)=>operation.verification.physical==='unverified')).toBe(true);
    }
    const blockers=(plan:any)=>plan.diagnostics.filter((d:any)=>d.severity==='error').map((d:any)=>[d.code,[...d.partIds].sort()]).sort((a:any,b:any)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));
    expect(blockers(restored)).toEqual(blockers(original));
    const reordered=computeAssemblyPlan(m,{...config,order:[...config.order].reverse()});expect(interfaces(reordered)).toEqual(interfaces(original));expect(physicalKinds(reordered)).toEqual(physicalKinds(original));
    for(const region of restored.regions)expect([...region.partIds].sort()).toEqual([...original.regions.find((old:any)=>old.id===region.id)!.partIds].sort());
  },30000);
});
describe('ordered build methods',()=>{
  it('closes a square by moving a subframe rather than forcing the final tube into two fixed ends',()=>{const {m}=square(),p=computeAssemblyPlan(m);expect(p.diagnostics.filter((d:any)=>d.code.includes('CLOSURE'))).toEqual([]);const ops=p.steps.flatMap((s:any)=>s.operations);expect(ops.some((o:any)=>o.type==='join-subframes'&&o.closureMethod==='common-axis-subframe-join')).toBe(true);expect(ops.filter((o:any)=>o.type==='insert-tube').every((o:any)=>o.openPorts?.length)).toBe(true);const step=p.steps[0],group=step.detailGroups[0],state=assemblyDetailState(p,0,group.id,{action:false});const future=step.operations.slice(3).flatMap((o:any)=>o.consumesPartIds);expect(future.filter((id:string)=>!group.partIds.includes(id)).every((id:string)=>!state.visible.has(id))).toBe(true);});
  it('orders continuous cloth threading before both carrier insertions and never claims an unchecked thread method',()=>{const {m,tubes}=square(),tx=m.addTextile(tubes[0].id,tubes[2].id,0,40,'blue')!;const steps=stepsFor(m);steps[3].textileIds=[tx.id];steps[3].partIds.push(tx.id);scheduleAssemblyAccessories(m,steps,[]);expect(steps[0].textileIds).toContain(tx.id);expect(steps.slice(1).some(s=>s.textileIds.includes(tx.id))).toBe(false);const p=computeAssemblyPlan(m),ops=p.steps.flatMap((s:any)=>s.operations),thread=ops.find((o:any)=>o.type==='prethread-accessory'&&o.partIds.includes(tx.id))!;expect(thread.carrierPartIds.sort()).toEqual([tubes[0].id,tubes[2].id].sort());for(const id of thread.carrierPartIds)expect(ops.indexOf(thread)).toBeLessThan(ops.findIndex((o:any)=>o.type==='insert-tube'&&o.partIds.includes(id)));expect(thread.translation.every(Number.isFinite)).toBe(true);expect(thread.verification.methodChecked).toBe(true);expect(ops.filter((o:any)=>o.consumesPartIds.includes(tx.id))).toHaveLength(1);if(!thread.verification.methodChecked)expect(p.diagnostics.some((d:any)=>d.code==='PRETHREAD_METHOD_UNVERIFIED'&&d.partIds.includes(tx.id))).toBe(true);});
  it('threads a floating wheel through its tube but requires an explicit bearing for a multifunction wheel',()=>{const {m,tubes}=square(),floating:any=m.addFitting('floating-wheel2',20,0,0)!,multi=m.addFitting('multi-wheel2',20,0,40)!;floating.tube=tubes[0].id;const steps=stepsFor(m);steps[3].fittingIds=[floating.id,multi.id];steps[3].partIds.push(floating.id,multi.id);const diagnostics:any[]=[];scheduleAssemblyAccessories(m,steps,diagnostics);expect(steps[0].fittingIds).toContain(floating.id);expect(diagnostics.some(d=>d.code==='MISSING_WHEEL_BEARING'&&d.partIds.includes(multi.id))).toBe(true);});
  it('places a panel after all its perimeter support tubes and before a subsequent riser',()=>{const {m,n,tubes}=square(),panel=m.addPanel(tubes[0].id,tubes[2].id,0,40,'panel_40x40','blue')!;const top=m.addNode(0,40,0),riser=m.addTube(n[0].id,top.id,'T35','blue',35)!;const steps=stepsFor(m);steps.push({...steps[0],id:'cover',partIds:[panel.id],tubeIds:[],panelIds:[panel.id]});scheduleAssemblyAccessories(m,steps,[]);expect(steps.findIndex(s=>s.panelIds.includes(panel.id))).toBeLessThan(steps.findIndex(s=>s.tubeIds.includes(riser.id)));expect(steps.flatMap(s=>s.panelIds)).toEqual([panel.id]);});
  it('blocks an unknown accessory geometry instead of certifying an arbitrary bounding cube',()=>{const {m}=square();m.addFitting('unrecognised-installation',20,10,20);const p=computeAssemblyPlan(m);expect(p.canExport).toBe(false);expect(p.diagnostics.some((d:any)=>d.code==='UNKNOWN_INSTALLATION_GEOMETRY')).toBe(true);expect(p.verification.methodChecked).toBe(false);});
  it('does not certify an unknown mounting method merely because a bounding box was supplied',()=>{const {m}=square();m.addFitting('unrecognised-installation',100,10,20,{w:1,h:1,d:1});const p=computeAssemblyPlan(m);expect(p.canExport).toBe(false);expect(p.diagnostics.some((d:any)=>d.code==='UNKNOWN_INSTALLATION_GEOMETRY')).toBe(true);expect(p.verification.methodChecked).toBe(false);});
});

const poolFrame=()=>{const m=new BuildModel(),left=[0,40,80,120].map(z=>m.addNode(-40,40,z)),right=[0,40,80,120].map(z=>m.addNode(40,40,z)),tubes=[m.addTube(left[0].id,right[0].id,'T75','blue',75)!,m.addTube(left[3].id,right[3].id,'T75','blue',75)!];for(const side of [left,right])for(let i=0;i<3;i++)tubes.push(m.addTube(side[i].id,side[i+1].id,'T35','blue',35)!);const liner=m.addFitting('pool-small2',0,40,0,{w:80,h:20,d:120})!;return {m,tubes,liner};};
describe('official flexible liner methods',()=>{
  it('threads every edge tube on its own axis before closure and then checks the expanded liner',()=>{const {m,tubes,liner}=poolFrame(),p=computeAssemblyPlan(m),ops=p.steps.flatMap((s:any)=>s.operations),threads=ops.filter((op:any)=>op.type==='thread-flexible-carrier');expect(threads).toHaveLength(tubes.length);expect(new Set(threads.map((op:any)=>op.carrierPartIds[0]))).toEqual(new Set(tubes.map(t=>t.id)));expect(new Set(threads.map((op:any)=>op.direction.map(Math.abs).join(','))).size).toBe(2);for(const op of threads){expect(op.verification.methodChecked,JSON.stringify(p.diagnostics.map((d:any)=>({code:d.code,parts:d.partIds})))).toBe(true);const carrier=op.carrierPartIds[0];expect(ops.indexOf(op)).toBeLessThan(ops.findIndex((later:any)=>later.type==='insert-tube'&&later.partIds.includes(carrier)));expect(op.verification.deformationValidation).toMatch(/not-simulated/);}const unfold=ops.find((op:any)=>op.type==='unfold-flexible-liner');expect(unfold).toBeDefined();expect(unfold.verification.pathChecked,JSON.stringify(p.diagnostics)).toBe(true);expect(p.canExport,JSON.stringify(p.diagnostics.map((d:any)=>({code:d.code,parts:d.partIds})))).toBe(true);expect(ops.filter((op:any)=>op.consumesPartIds.includes(liner.id))).toHaveLength(1);},30000);
  it('blocks a missing perimeter edge before claiming the liner can be installed',()=>{const {m,tubes,liner}=poolFrame();m.tubes.delete(tubes.at(-1)!.id);const p=computeAssemblyPlan(m);expect(p.canExport).toBe(false);expect(p.diagnostics.some((d:any)=>d.code==='MISSING_THREAD_SUPPORT'&&d.partIds.includes(liner.id))).toBe(true);},30000);
  it('blocks prethreading after one perimeter edge has been separated into an earlier closing region',()=>{const {m,tubes,liner}=poolFrame(),first=tubes[0],early=[first.id,first.a,first.b],rest=[...m.nodes.keys(),...m.tubes.keys(),liner.id].filter(id=>!early.includes(id)),p=computeAssemblyPlan(m,{version:1,regions:[{id:'early-closed-edge',partIds:early},{id:'remaining-liner-frame',partIds:rest}],order:['early-closed-edge','remaining-liner-frame']});expect(p.canExport).toBe(false);expect(p.diagnostics.some((d:any)=>d.code==='PRETHREAD_METHOD_UNVERIFIED'&&d.partIds.includes(liner.id)&&d.details?.open===false)).toBe(true);},30000);
});

const coveredFrame=()=>{const {m,n}=square(),tops=n.map(v=>m.addNode(v.x,40,v.z));for(let i=0;i<4;i++){m.addTube(n[i].id,tops[i].id,'T35','blue',35);m.addTube(tops[i].id,tops[(i+1)%4].id,'T35','blue',35);}const ceiling=[[-20,80,-20],[60,80,-20],[60,80,60],[-20,80,60]].map(v=>m.addNode(...v)),feet=ceiling.map(n=>m.addNode(n.x,0,n.z)),outer=[];for(let i=0;i<4;i++){outer.push(m.addTube(feet[i].id,feet[(i+1)%4].id,'T75','blue',75)!,m.addTube(feet[i].id,ceiling[i].id,'T75','blue',75)!);}const rails=ceiling.map((v,i)=>m.addTube(v.id,ceiling[(i+1)%4].id,'T75','blue',75)!),panel=m.addPanel(rails[0].id,rails[2].id,0,80,'panel_80x80','blue')!,ceilingIds=[...ceiling.map(n=>n.id),...feet.map(n=>n.id),...outer.map(t=>t.id),...rails.map(t=>t.id),panel.id],bodyIds=[...m.nodes.keys(),...m.tubes.keys()].filter(id=>!ceilingIds.includes(id));return {m,panel,bodyIds,ceilingIds};};
describe('blocked lowering alternatives',()=>{
  it('defers a covering that blocks lowering, replans the actual frame, and fits the covering afterwards',()=>{const {m,panel,bodyIds,ceilingIds}=coveredFrame(),p=computeAssemblyPlan(m,{version:1,regions:[{id:'ceiling',partIds:ceilingIds},{id:'body',partIds:bodyIds}],order:['ceiling','body']}),ops=p.steps.flatMap((s:any)=>s.operations),lower=ops.findIndex((op:any)=>op.type==='lower-frame'),fit=ops.findIndex((op:any)=>op.type==='fit-accessory'&&op.partIds.includes(panel.id));expect(p.adjustments.some((a:any)=>a.partId===panel.id)).toBe(true);expect(lower).toBeGreaterThanOrEqual(0);expect(fit).toBeGreaterThan(lower);expect(p.canExport,JSON.stringify(p.diagnostics.map((d:any)=>({code:d.code,parts:d.partIds})))).toBe(true);expect(ops.filter((op:any)=>op.consumesPartIds.includes(panel.id))).toHaveLength(1);const step=p.steps.find((s:any)=>s.operations.includes(ops[fit]))!,group=step.detailGroups.find((g:any)=>g.operationIds.includes(ops[fit].id))!,before=assemblyDetailState(p,p.steps.indexOf(step),group.id,{action:true}),after=assemblyDetailState(p,p.steps.indexOf(step),group.id,{action:false}),overview=assemblyState(p,p.steps.length-1);expect(p.regions.find((r:any)=>r.id==='body')!.panelIds).toContain(panel.id);expect(p.regions.find((r:any)=>r.id==='ceiling')!.panelIds).not.toContain(panel.id);expect(before.transforms.get(panel.id)).toEqual(ops[fit].translation.map((v:number)=>v===0?0:v));expect(after.transforms.get(panel.id)).toEqual(overview.transforms.get(panel.id));expect(after.visible.has(panel.id)&&overview.visible.has(panel.id)).toBe(true);});
  it('blocks a rigid obstruction when no covering can be delayed to open the lowering route',()=>{const {m,panel,bodyIds,ceilingIds}=coveredFrame();m.panels.delete(panel.id);const a=m.addNode(20,0,0),b=m.addNode(20,80,0),bar=m.addTube(a.id,b.id,'T75','red',75)!;const p=computeAssemblyPlan(m,{version:1,regions:[{id:'obstruction',partIds:[a.id,b.id,bar.id]},{id:'body',partIds:bodyIds},{id:'ceiling',partIds:ceilingIds.filter(id=>id!==panel.id)}],order:['obstruction','body','ceiling']});expect(p.canExport).toBe(false);expect(p.frameModules.some((module:any)=>module.reason==='installation-path-blocked'&&module.obstruction.obstaclePartId===bar.id)).toBe(true);expect(p.diagnostics.some((d:any)=>d.code==='INSTALLATION_PATH_BLOCKED'&&d.partIds.includes(bar.id))).toBe(true);expect(p.verification.pathChecked).toBe(false);});
});

describe('operation direction evidence',()=>{
  const directionPlan=(translation:number[],direction:number[])=>{const m=new BuildModel(),a=m.addNode(0,0,0),b=m.addNode(40,0,0),t=m.addTube(a.id,b.id,'T35','blue',35)!,ids=[a.id,b.id,t.id],base={regionId:'body',y:0,partIds:ids,nodeIds:[a.id,b.id],tubeIds:[t.id],panelIds:[],fittingIds:[],textileIds:[],slideIds:[],clampIds:[],dependsOn:[],instructions:[],parts:{reinforcements:[]}},plan:any={steps:[{...base,id:'build',action:{type:'build'}},{...base,id:'attach',action:{type:'attach'}}],regions:[{id:'body',tubeIds:[t.id],detachedTranslation:translation,installation:{direction,pathVerified:true}}],frameModules:[],interfaces:[],diagnostics:[],ledger:{instances:[]}};addAssemblyOperations(m,plan);return plan;};
  it('reports the exact action when its direction differs from the displacement',()=>{const p=directionPlan([0,12,0],[1,0,0]);expect(p.verification.directionChecked).toBe(false);expect(p.diagnostics.find((d:any)=>d.code==='INVALID_OPERATION_DIRECTION')?.details.operationId).toBe('attach-operation-1');});
  it('treats a zero displacement as no direction to compare while checking its static shape',()=>{const p=directionPlan([0,0,0],[0,-1,0]),op=p.steps[1].operations[0];expect(op.verification.directionApplicability).toBe('not-applicable');expect(op.verification.directionConsistent).toBe(true);expect(op.verification.pathChecked).toBe(true);expect(p.diagnostics.some((d:any)=>d.code==='INVALID_OPERATION_DIRECTION')).toBe(false);});
});

describe('preclosed dependencies and blocked paths',()=>{
  it('prethreads both closed-ring axes and moves the carriers together before either endpoint is closed',()=>{const m=new BuildModel(),nodes=[[0,0,0],[40,0,0],[0,0,5],[40,0,5]].map(v=>m.addNode(...v)),a=m.addTube(nodes[0].id,nodes[1].id,'T35','blue',35)!,b=m.addTube(nodes[2].id,nodes[3].id,'T35','blue',35)!,c:any=m.addClamp(20,0,0,'double_tube');c.dir=[1,0,0];c.off=[0,0,5];const p=computeAssemblyPlan(m,{version:1,regions:[{id:'open-ring-workgroup',partIds:[...nodes.map(n=>n.id),a.id,b.id,c.id]}]}),ops=p.steps.flatMap((s:any)=>s.operations),thread=ops.find((o:any)=>o.type==='prethread-accessory'&&o.partIds.includes(c.id))!;expect(thread.carrierPartIds.sort()).toEqual([a.id,b.id].sort());expect(thread.verification.methodChecked).toBe(true);const firstInsert=ops.findIndex((o:any)=>o.type==='insert-tube'&&o.partIds.includes(a.id));expect(ops.indexOf(thread)).toBeLessThan(firstInsert);expect(ops[firstInsert].partIds).toContain(b.id);for(const n of nodes)expect(ops.findIndex((o:any)=>(o.type==='join-subframes'&&o.closesPorts?.includes(n.id))||(o.type==='insert-tube'&&o.referencePartIds?.includes(n.id)))).toBeGreaterThan(ops.indexOf(thread));expect(ops.filter((o:any)=>o.consumesPartIds.includes(c.id))).toHaveLength(1);});
  it('threads an 80 cm wood profile into the open first carrier before the middle connector and second carrier close',()=>{const m=new BuildModel(),a=m.addNode(0,0,0),b=m.addNode(0,40,0),c=m.addNode(0,80,0),t=m.addTube(a.id,b.id,'T35','blue',35)!,u=m.addTube(b.id,c.id,'T35','blue',35)!;t.reinforced=true;u.reinforced=true;const p=computeAssemblyPlan(m),ops=p.steps.flatMap((s:any)=>s.operations),at=(type:string)=>ops.findIndex((o:any)=>o.type===type),core=at('preinsert-reinforcement'),first=ops.findIndex((o:any)=>o.consumesPartIds.includes(t.id)),second=ops.findIndex((o:any)=>o.consumesPartIds.includes(u.id)),middle=ops.findIndex((o:any)=>o.type==='thread-core-connector'&&o.partIds.includes(b.id));expect(core).toBeGreaterThan(first);expect(middle).toBeGreaterThan(core);expect(second).toBeGreaterThan(middle);expect(ops[core].protrusionCm).toBe(40);expect(p.diagnostics).toEqual([]);expect(p.canExport).toBe(true);expect(ops[core].verification.basis).toMatch(/official/);expect(ops[core].instructions.join(' ')).toMatch(/wood|木|Holz/);const material=(p.ledger.instances as any[]).find((i:any)=>i.group==='reinforcements')!,takingStep=p.steps.find((s:any)=>s.operations.includes(ops[core]))!;expect(material.stepId).toBe(takingStep.id);expect(takingStep.parts.reinforcements.reduce((sum:number,row:any)=>sum+row.count,0)).toBe(1);expect(p.steps.reduce((sum:number,step:any)=>sum+step.parts.reinforcements.reduce((sum:number,row:any)=>sum+row.count,0),0)).toBe(1);expect(ops[middle].dependsOn).toContain(ops[core].id);const step=p.steps.find((s:any)=>s.operations.some((o:any)=>o.id===ops[core].id))!,group=step.detailGroups.find((g:any)=>g.operationIds.includes(ops[core].id))!,before=assemblyDetailState(p,p.steps.indexOf(step),group.id,{action:true}),after=assemblyDetailState(p,p.steps.indexOf(step),group.id,{action:false});expect(before.transforms.get(t.id)).toEqual(after.transforms.get(t.id));expect(before.profileTransforms.get(t.id)).not.toEqual(after.profileTransforms.get(t.id));});
  it('blocks a 60 cm reinforcement column with specific carrier diagnostics',()=>{const m=new BuildModel(),nodes=[0,20,40,60].map(y=>m.addNode(0,y,0));for(let i=0;i<3;i++)m.addTube(nodes[i].id,nodes[i+1].id,'T15','blue',15)!.reinforced=true;const p=computeAssemblyPlan(m);expect(p.canExport).toBe(false);expect(p.diagnostics.some((d:any)=>d.code==='REINFORCEMENT_PLACEMENT_UNVERIFIED'&&d.details?.span===60&&d.partIds.length>=3)).toBe(true);expect(p.verification.methodChecked).toBe(false);});
  it('limits wood-profile compatibility to the actual coaxial channel during motion',()=>{const m=new BuildModel(),a=m.addNode(0,0,0),b=m.addNode(0,40,0),c=m.addNode(0,80,0),t=m.addTube(a.id,b.id,'T35','blue',35)!,u=m.addTube(b.id,c.id,'T35','blue',35)!;t.reinforced=true;u.reinforced=true;const core=createCoreChannels(m),channel=core.channels[0];channel.active=true;expect(core.check([channel.id],[t.id],[0,40,0],[0,0,0])).toBeNull();expect(core.check([channel.id],[t.id],[0,0,0],[1,0,0])).not.toBeNull();expect(core.check([channel.id],[t.id],[0,40,0],[0,0,0],{obstacleTranslations:new Map([[t.id,[1,0,0]]])})).not.toBeNull();});
  it('fails closed when an installed plate intercepts a falling pipe',async()=>{const {m,tubes}=square(),panel=m.addPanel(tubes[0].id,tubes[2].id,0,40,'panel_40x40','blue')!;const a=m.addNode(20,20,20),b=m.addNode(20,60,20),pipe=m.addTube(a.id,b.id,'T35','blue',35)!;const {checkAssemblyPath}=await import('./assemblyCollision.js');expect(checkAssemblyPath(m,[pipe.id],[panel.id],[0,0,0],[0,-40,0])).toMatchObject({movingPartId:pipe.id,obstaclePartId:panel.id});});
});


describe('native mounting methods',()=>{
  it('blocks a standard panel when only a sideways route is clear but its actual normal approach is obstructed',async()=>{const {m,n}=square(),upper=n.map(n=>m.addNode(n.x,40,n.z));for(let i=0;i<4;i++)m.addTube(n[i].id,upper[i].id,'T35','blue',35);const rails=upper.map((n,i)=>m.addTube(n.id,upper[(i+1)%4].id,'T35','blue',35)!),base=[...m.nodes.keys(),...m.tubes.keys()],panel=m.addPanel(rails[0].id,rails[2].id,0,40,'panel_40x40','blue')!,feet=[m.addNode(-20,0,20),m.addNode(60,0,20)],mids=feet.map(n=>m.addNode(n.x,30,n.z)),tops=feet.map(n=>m.addNode(n.x,50,n.z)),legs=feet.flatMap((n,i)=>[m.addTube(n.id,mids[i].id,'T25','blue',25)!,m.addTube(mids[i].id,tops[i].id,'T15','blue',15)!]),bar=m.addTube(tops[0].id,tops[1].id,'T75','blue',75)!,obstruction=[...feet.map(n=>n.id),...mids.map(n=>n.id),...tops.map(n=>n.id),...legs.map(t=>t.id),bar.id],{checkAssemblyPath}=await import('./assemblyCollision.js');expect(checkAssemblyPath(m,[panel.id],obstruction,[8,0,0],[0,0,0])).toBeNull();const p=computeAssemblyPlan(m,{version:1,regions:[{id:'supported-bridge',partIds:obstruction},{id:'panel-frame',partIds:[...base,panel.id]}],order:['supported-bridge','panel-frame']});expect(p.canExport).toBe(false);expect(p.diagnostics.some((d:any)=>d.code==='ACCESSORY_INSTALLATION_PATH_UNRESOLVED'&&d.partIds.includes(panel.id))).toBe(true);});
  it('accepts a supported roof but rejects the same roof turned upside down around its ridge',()=>{const m=new BuildModel(),a=m.addNode(0,100,0),b=m.addNode(80,100,0),middle=m.addNode(40,100,0);m.addTube(a.id,middle.id,'T35','blue',35);m.addTube(middle.id,b.id,'T35','blue',35);for(const node of [a,b])for(const sign of [-1,1]){const eave=m.addNode(node.x,60,40*sign);m.addTube(node.id,eave.id,'T55','blue',55);}const mount=m.roofMounts('roof2',true)[0];expect(mount).toBeDefined();const roof=m.addRoofAt(mount)!;expect(nativeAccessorySupport(m,roof.id).valid).toBe(true);roof.quat=[mount.quat[3],-mount.quat[2],mount.quat[1],-mount.quat[0]];expect(nativeAccessorySupport(m,roof.id).valid).toBe(false);});

  it('rejects a known native fitting without a real mounting position even when its path is clear',()=>{const {m}=square(),f=m.addFitting('bearing2',100,10,20)!,p=computeAssemblyPlan(m),op=p.steps.flatMap((s:any)=>s.operations).find((op:any)=>op.partIds.includes(f.id))!;expect(p.canExport).toBe(false);expect(p.diagnostics.some((d:any)=>d.code==='NATIVE_SUPPORT_UNRESOLVED'&&d.partIds.includes(f.id))).toBe(true);expect(op.verification.pathChecked).toBe(true);expect(op.verification.methodChecked).toBe(false);});
  it('installs the bearing on its actual free port before the wheel slides onto its shaft',()=>{const m=new BuildModel(),a=m.addNode(0,40,0),b=m.addNode(0,0,0),c=m.addNode(0,40,40);m.addTube(a.id,b.id,'T35','blue',35);m.addTube(a.id,c.id,'T35','blue',35);const bearing=m.addFitting('bearing2',0,40,0,{quat:[0,0,0,1]})!,wheel=m.addFitting('multi-wheel2',5,40,0,{quat:[0,0,0,1]})!,p=computeAssemblyPlan(m),ops=p.steps.flatMap((s:any)=>s.operations),bearingOp=ops.find((op:any)=>op.type==='fit-accessory'&&op.partIds.includes(bearing.id))!,wheelOp=ops.find((op:any)=>op.type==='fit-accessory'&&op.partIds.includes(wheel.id))!;expect(p.canExport,JSON.stringify(p.diagnostics)).toBe(true);expect(ops.indexOf(bearingOp)).toBeLessThan(ops.indexOf(wheelOp));expect(bearingOp.referencePartIds).toContain(a.id);expect(wheelOp.referencePartIds).toContain(bearing.id);expect([bearingOp,wheelOp].every(op=>op.verification.methodChecked&&op.verification.pathChecked)).toBe(true);expect(wheelOp.translation).toEqual([18,0,0]);for(const id of [bearing.id,wheel.id])expect(ops.filter((op:any)=>op.consumesPartIds.includes(id))).toHaveLength(1);});
  it('uses the normalized native wheel rotation for the actual shaft approach',()=>{
    const m=new BuildModel(),a=m.addNode(0,40,0),b=m.addNode(0,0,0),c=m.addNode(-40,40,0);
    m.addTube(a.id,b.id,'T35','blue',35);m.addTube(a.id,c.id,'T35','blue',35);
    const quat=[0,-.7071,0,.7071],bearing=m.addFitting('bearing2',0,40,0,{quat})!,wheel=m.addFitting('multi-wheel2',0,40,5,{quat})!,p=computeAssemblyPlan(m),ops=p.steps.flatMap((s:any)=>s.operations);
    expect(p.canExport,JSON.stringify(p.diagnostics)).toBe(true);
    const shaft=ops.find((op:any)=>op.type==='fit-accessory'&&op.partIds.includes(wheel.id))!;
    expect(shaft.referencePartIds).toContain(bearing.id);
    expect(shaft.translation[0]).toBeCloseTo(0,12);expect(shaft.translation[1]).toBeCloseTo(0,12);expect(shaft.translation[2]).toBeCloseTo(18,12);
    expect(shaft.verification.methodChecked&&shaft.verification.pathChecked).toBe(true);
  });
  it('resolves a bearing with no tube reference using the actual free connector port',()=>{const m=new BuildModel(),a=m.addNode(0,40,0),b=m.addNode(0,0,0),c=m.addNode(0,40,40);m.addTube(a.id,b.id,'T35','blue',35);m.addTube(a.id,c.id,'T35','blue',35);const f=m.addFitting('bearing2',0,40,0)!;expect((f as any).tube).toBeFalsy();expect(nativeAccessorySupport(m,f.id)).toMatchObject({valid:true,supportIds:[a.id],mount:{position:[0,40,0],direction:[1,0,0]}});});
});
