export const sharedStrings = {
  zh: {
    'collab.join.invited': '{who}邀请你加入「{name}」',
    'collab.readOnly.guest': '{owner}的共享方案。通过创建人的邀请链接登录加入后，可按授权参与。',
    'collab.readOnly.login': '登录',
    'coach.login.body': '现在可以转着看，读评论和留言。通过创建人的邀请链接登录加入后，可按邀请权限编辑或评论。',
    'coach.join.body': '你还不是这个方案的成员。请创建人发邀请链接给你，加入后可按邀请权限编辑或评论。',
    'collab.create.action': '创建共享方案',
    'collab.create.title': '新建共享方案',
    'collab.create.subtitle': '从一份造型开始，邀请伙伴一起编辑。',
    'collab.create.copy': '复制当前造型',
    'collab.create.copyHint': '保留模型，独立保存',
    'collab.create.blank': '从空白开始',
    'collab.create.blankHint': '和伙伴一起搭建',
    'collab.create.sourceHint': '以当前画面创建独立副本',
    'collab.create.name': '方案名称',
    'collab.create.nameLimit': '方案名称为 1 至 40 个字符',
    'collab.create.blankName': '新的共享方案',
    'collab.create.copyName': '{name} · 共享方案',
    'collab.create.independent': '新方案独立保存，修改不会同步到原设计或广场作品。',
    'collab.create.go': '创建并邀请',
    'collab.create.creating': '正在创建…',
    'collab.create.login': '登录后创建',
    'collab.create.recover': '打开已创建的方案',
    'collab.create.coverFailed': '方案已创建，封面暂未保存。可以在此重试。',
    'collab.create.retryCover': '重新保存封面',
    'collab.create.coverSaved': '封面已保存',
    'collab.create.invite': '邀请协作',
    'collab.create.members': '查看成员',
    'collab.create.owner': '方案创建人',
    'collab.create.role.owner': '创建人',
    'collab.create.role.editor': '可编辑',
    'collab.create.role.commenter': '可评论',
    'collab.create.memberRole': '{name}的权限',
    'collab.create.removeName': '移除{name}',
    'collab.create.tab.invite': '邀请',
    'collab.create.tab.members': '成员',
    'collab.create.tab.view': '分享查看',
    'collab.create.inviteBanner': '邀请伙伴，一起完成这份方案',
    'collab.create.onlyOwner': '只有创建人可以邀请和调整权限',
    'collab.create.permission': '对方加入后可以',
    'collab.create.inviteRole.editor': '一起编辑',
    'collab.create.inviteRole.commenter': '查看和评论',
    'collab.create.inviteHint.editor': '加入后可以修改造型、评论和保存版本。',
    'collab.create.inviteHint.commenter': '加入后可以查看造型、评论和留言。',
    'collab.create.copyInvite.editor': '复制编辑邀请链接',
    'collab.create.copyInvite.commenter': '复制评论邀请链接',
    'collab.create.previewInvite': '查看对方收到的邀请',
    'collab.create.disable': '停用此邀请链接',
    'collab.create.disableTitle': '停用这条邀请链接？',
    'collab.create.disableBody': '持有这条链接的人将无法继续通过它加入。已加入成员的权限保持不变。',
    'collab.create.noLink': '当前权限没有有效邀请链接。已加入成员的权限保持不变。',
    'collab.create.generate': '生成新的邀请链接',
    'collab.create.joinedMembers': '已加入的成员',
    'collab.create.manageMembers': '管理成员与权限 →',
    'collab.create.manageHint': '调整成员的编辑权限，或将成员移出这份方案。',
    'collab.create.memberHint': '你可以查看成员；邀请和权限由创建人管理。',
    'collab.create.removeTitle': '移除成员？',
    'collab.create.removeBody': '{name}将失去这份共享方案的成员权限。',
    'collab.create.viewTitle': '让别人看看这份方案',
    'collab.create.viewHint': '查看链接可打开方案预览，不授予编辑或评论权限。',
    'collab.create.copyView': '复制查看链接',
    'collab.create.joined': '你已加入，权限：{role}',
  },
  en: {
    'collab.join.invited': '{who} invited you to join “{name}”',
    'collab.readOnly.guest': '{owner}’s shared plan. Sign in through the creator’s invitation to join with the granted permission.',
    'collab.readOnly.login': 'Sign in',
    'coach.login.body': 'You can view the model and read comments and chat. Sign in through an invitation from the creator to edit or comment with the granted permission.',
    'coach.join.body': 'You are not a member yet. Ask the creator for an invitation to edit or comment with the granted permission.',
    'collab.create.action': 'Create shared plan',
    'collab.create.title': 'New shared plan',
    'collab.create.subtitle': 'Start with a design and invite others to build together.',
    'collab.create.copy': 'Copy current design',
    'collab.create.copyHint': 'Keep the model, save separately',
    'collab.create.blank': 'Start from blank',
    'collab.create.blankHint': 'Build together from scratch',
    'collab.create.sourceHint': 'Create a separate copy of the current model',
    'collab.create.name': 'Plan name',
    'collab.create.nameLimit': 'Plan names must contain 1 to 40 characters',
    'collab.create.blankName': 'New shared plan',
    'collab.create.copyName': '{name} · Shared plan',
    'collab.create.independent': 'The new plan is saved separately. Changes do not affect the original design or plaza work.',
    'collab.create.go': 'Create and invite',
    'collab.create.creating': 'Creating…',
    'collab.create.login': 'Sign in to create',
    'collab.create.recover': 'Open the created plan',
    'collab.create.coverFailed': 'The plan was created, but its cover could not be saved. You can retry here.',
    'collab.create.retryCover': 'Save cover again',
    'collab.create.coverSaved': 'Cover saved',
    'collab.create.invite': 'Invite collaborators',
    'collab.create.members': 'View members',
    'collab.create.owner': 'Plan creator',
    'collab.create.role.owner': 'Creator',
    'collab.create.role.editor': 'Can edit',
    'collab.create.role.commenter': 'Can comment',
    'collab.create.memberRole': 'Permission for {name}',
    'collab.create.removeName': 'Remove {name}',
    'collab.create.tab.invite': 'Invite',
    'collab.create.tab.members': 'Members',
    'collab.create.tab.view': 'Share for viewing',
    'collab.create.inviteBanner': 'Invite others to finish this plan together',
    'collab.create.onlyOwner': 'Only the creator can invite and manage permissions',
    'collab.create.permission': 'After joining, they can',
    'collab.create.inviteRole.editor': 'Edit together',
    'collab.create.inviteRole.commenter': 'View and comment',
    'collab.create.inviteHint.editor': 'Members can edit the model, comment and save versions.',
    'collab.create.inviteHint.commenter': 'Members can view the model, comment and chat.',
    'collab.create.copyInvite.editor': 'Copy editing invitation',
    'collab.create.copyInvite.commenter': 'Copy commenting invitation',
    'collab.create.previewInvite': 'View the invitation they receive',
    'collab.create.disable': 'Disable this invitation link',
    'collab.create.disableTitle': 'Disable this invitation link?',
    'collab.create.disableBody': 'People can no longer join using this link. Existing members keep their permissions.',
    'collab.create.noLink': 'No active invitation link for this permission. Existing members keep their permissions.',
    'collab.create.generate': 'Generate a new invitation link',
    'collab.create.joinedMembers': 'Members who have joined',
    'collab.create.manageMembers': 'Manage members and permissions →',
    'collab.create.manageHint': 'Change editing permissions or remove members from this plan.',
    'collab.create.memberHint': 'You can view members. The creator manages invitations and permissions.',
    'collab.create.removeTitle': 'Remove member?',
    'collab.create.removeBody': '{name} will lose membership access to this shared plan.',
    'collab.create.viewTitle': 'Let others view this plan',
    'collab.create.viewHint': 'The viewing link opens a preview. It grants no editing or commenting permissions.',
    'collab.create.copyView': 'Copy viewing link',
    'collab.create.joined': 'You have joined with permission: {role}',
  },
  de: {
    'collab.join.invited': '{who} lädt dich ein, „{name}“ beizutreten',
    'collab.readOnly.guest': 'Gemeinsamer Plan von {owner}. Über die Einladung des Erstellers anmelden und mit der erteilten Berechtigung beitreten.',
    'collab.readOnly.login': 'Anmelden',
    'coach.login.body': 'Du kannst das Modell ansehen sowie Kommentare und Nachrichten lesen. Über eine Einladung des Erstellers anmelden, um mit der erteilten Berechtigung zu bearbeiten oder zu kommentieren.',
    'coach.join.body': 'Du bist noch kein Mitglied. Bitte den Ersteller um eine Einladung, um mit der erteilten Berechtigung zu bearbeiten oder zu kommentieren.',
    'collab.create.action': 'Gemeinsamen Plan erstellen',
    'collab.create.title': 'Neuer gemeinsamer Plan',
    'collab.create.subtitle': 'Mit einem Entwurf beginnen und andere zum gemeinsamen Bauen einladen.',
    'collab.create.copy': 'Aktuellen Entwurf kopieren',
    'collab.create.copyHint': 'Modell behalten, separat speichern',
    'collab.create.blank': 'Leer beginnen',
    'collab.create.blankHint': 'Gemeinsam von Anfang an bauen',
    'collab.create.sourceHint': 'Eine separate Kopie des aktuellen Modells erstellen',
    'collab.create.name': 'Name des Plans',
    'collab.create.nameLimit': 'Der Planname muss 1 bis 40 Zeichen enthalten',
    'collab.create.blankName': 'Neuer gemeinsamer Plan',
    'collab.create.copyName': '{name} · Gemeinsamer Plan',
    'collab.create.independent': 'Der neue Plan wird separat gespeichert. Änderungen beeinflussen weder den ursprünglichen Entwurf noch den Beitrag im Modellplatz.',
    'collab.create.go': 'Erstellen und einladen',
    'collab.create.creating': 'Wird erstellt…',
    'collab.create.login': 'Zum Erstellen anmelden',
    'collab.create.recover': 'Erstellten Plan öffnen',
    'collab.create.coverFailed': 'Der Plan wurde erstellt, das Titelbild konnte jedoch nicht gespeichert werden. Du kannst es hier erneut versuchen.',
    'collab.create.retryCover': 'Titelbild erneut speichern',
    'collab.create.coverSaved': 'Titelbild gespeichert',
    'collab.create.invite': 'Zur Zusammenarbeit einladen',
    'collab.create.members': 'Mitglieder anzeigen',
    'collab.create.owner': 'Ersteller des Plans',
    'collab.create.role.owner': 'Ersteller',
    'collab.create.role.editor': 'Darf bearbeiten',
    'collab.create.role.commenter': 'Darf kommentieren',
    'collab.create.memberRole': 'Berechtigung für {name}',
    'collab.create.removeName': '{name} entfernen',
    'collab.create.tab.invite': 'Einladen',
    'collab.create.tab.members': 'Mitglieder',
    'collab.create.tab.view': 'Zum Ansehen teilen',
    'collab.create.inviteBanner': 'Andere einladen, diesen Plan gemeinsam fertigzustellen',
    'collab.create.onlyOwner': 'Nur der Ersteller kann einladen und Berechtigungen verwalten',
    'collab.create.permission': 'Nach dem Beitritt dürfen sie',
    'collab.create.inviteRole.editor': 'Gemeinsam bearbeiten',
    'collab.create.inviteRole.commenter': 'Ansehen und kommentieren',
    'collab.create.inviteHint.editor': 'Mitglieder können das Modell bearbeiten, kommentieren und Versionen speichern.',
    'collab.create.inviteHint.commenter': 'Mitglieder können das Modell ansehen, kommentieren und Nachrichten schreiben.',
    'collab.create.copyInvite.editor': 'Einladung zum Bearbeiten kopieren',
    'collab.create.copyInvite.commenter': 'Einladung zum Kommentieren kopieren',
    'collab.create.previewInvite': 'Einladung für andere ansehen',
    'collab.create.disable': 'Diesen Einladungslink deaktivieren',
    'collab.create.disableTitle': 'Diesen Einladungslink deaktivieren?',
    'collab.create.disableBody': 'Über diesen Link kann niemand mehr beitreten. Bestehende Mitglieder behalten ihre Berechtigungen.',
    'collab.create.noLink': 'Kein aktiver Einladungslink für diese Berechtigung. Bestehende Mitglieder behalten ihre Berechtigungen.',
    'collab.create.generate': 'Neuen Einladungslink erstellen',
    'collab.create.joinedMembers': 'Beigetretene Mitglieder',
    'collab.create.manageMembers': 'Mitglieder und Berechtigungen verwalten →',
    'collab.create.manageHint': 'Bearbeitungsrechte ändern oder Mitglieder aus diesem Plan entfernen.',
    'collab.create.memberHint': 'Du kannst Mitglieder ansehen. Einladungen und Berechtigungen verwaltet der Ersteller.',
    'collab.create.removeTitle': 'Mitglied entfernen?',
    'collab.create.removeBody': '{name} verliert den Mitgliederzugang zu diesem gemeinsamen Plan.',
    'collab.create.viewTitle': 'Andere diesen Plan ansehen lassen',
    'collab.create.viewHint': 'Der Link öffnet die Vorschau und erteilt keine Bearbeitungs- oder Kommentarrechte.',
    'collab.create.copyView': 'Ansichtslink kopieren',
    'collab.create.joined': 'Du bist beigetreten mit der Berechtigung: {role}',
  },
}
