import { expect, test, type Page } from '@playwright/test'

async function boot(page: Page) {
  await page.addInitScript(() => {
    localStorage.setItem('quadro.builder.onboarded.v2', '1')
    localStorage.setItem('quadro-builder-lang', 'zh')
  })
  await page.goto('/')
  await expect(page.locator('#canvas-host')).toHaveAttribute('data-ready', 'true')
}

async function hold(page: Page, x = 760, y = 450) {
  await page.mouse.move(x, y)
  await page.keyboard.down('4')
  await expect(page.locator('[data-holding="true"]')).toHaveCount(1)
  await expect(page.locator('.qb-components-pager')).not.toContainText('正在读取组件')
}

async function configure(page: Page) {
  await hold(page)
  await page.keyboard.up('4')
  await expect(page.locator('[data-configuring="true"]')).toHaveCount(1)
}

async function extendTo(page: Page, slot: number) {
  const center = await page.locator('[data-configure]').boundingBox()
  const target = await page.locator(`[data-slot="${slot}"]`).boundingBox()
  const cx = center!.x + center!.width / 2, cy = center!.y + center!.height / 2
  await page.mouse.move(cx + (target!.x + target!.width / 2 - cx) * 1.45, cy + (target!.y + target!.height / 2 - cy) * 1.45)
  await expect(page.locator(`[data-slot="${slot}"]`)).toHaveAttribute('data-active', 'true')
}

async function buildAndSelect(page: Page) {
  await page.getByRole('button', { name: '模型库', exact: true }).click()
  await page.getByRole('button', { name: '起步造型', exact: true }).click()
  await page.getByTitle('立方框 · 1×1×1', { exact: true }).click()
  await page.mouse.click(750, 470)
  await page.keyboard.press('Escape')
  await page.waitForFunction(() => window.__quadroDev.scene.selectableParts().size > 0)
  await page.keyboard.press('ControlOrMeta+a')
  await expect.poll(() => page.evaluate(() => window.__quadroDev.model.tubes.size)).toBe(12)
}

async function saveAndConfigure(page: Page, name: string) {
  await configure(page)
  await page.getByRole('button', { name: '保存选区与管理组件', exact: true }).click()
  await page.getByLabel('组件名称').fill(name)
  await page.getByRole('button', { name: '保存组件', exact: true }).click()
  await expect(page.locator('.qb-components-row', { hasText: name })).toHaveCount(1)
  await page.getByRole('button', { name: '保存选区与管理组件', exact: true }).click()
  await page.locator('.cc-mini-slot[data-index="6"]').click()
  await page.getByLabel('搜索名称或尺寸').fill(name)
  await page.locator('.cc-catalogue-card:not(:disabled)', { hasText: name }).click()
  await expect(page.locator('.cc-mini-slot[data-index="6"]')).toHaveAttribute('data-empty', 'false')
}

test('按住4方向选中，松开执行；圆外延伸、重复键、取消与原快捷键', async ({ page }) => {
  await boot(page)
  await page.keyboard.press('1')
  await page.keyboard.press('5')
  await page.keyboard.press('6')
  expect(await page.evaluate(() => window.__quadroDev.builder.tubeId)).toBe('T15')
  await hold(page)
  await page.keyboard.down('4')
  const center = await page.locator('[data-configure]').boundingBox()
  expect(Math.abs(center!.x + center!.width / 2 - 760)).toBeLessThan(4)
  expect(Math.abs(center!.y + center!.height / 2 - 450)).toBeLessThan(4)
  await extendTo(page, 0)
  expect(await page.evaluate(() => window.__quadroDev.builder.mode)).toBe('add')
  await page.keyboard.up('4')
  await expect(page.locator('[data-ui="custom-components"]')).toHaveCount(0)
  expect(await page.evaluate(() => [window.__quadroDev.builder.mode, window.__quadroDev.builder.panelId])).toEqual(['panel', 'panel_40x40'])
  await hold(page)
  await extendTo(page, 3)
  await expect(page.locator('.qb-components-wheel [role="status"]')).toContainText('松开 4，取消本次选择')
  await page.keyboard.up('4')
  await expect(page.locator('[data-ui="custom-components"]')).toHaveCount(0)
  expect(await page.evaluate(() => window.__quadroDev.builder.mode)).toBe('panel')
  await page.keyboard.press('3')
  expect(await page.evaluate(() => window.__quadroDev.builder.tubeId)).toBe('T35')
})

test('默认六项均接入对应真实放置模式', async ({ page }) => {
  await boot(page)
  const cases = [
    { slot: 1, mode: 'panel', field: 'panelId', value: 'hole_panel_40x40' },
    { slot: 2, mode: 'panel', field: 'panelId', value: 'panel_40x20' },
    { slot: 4, mode: 'clamp', field: 'clampPart', value: 'double_tube' },
    { slot: 5, mode: 'slide', field: 'slideKind', value: 'slide-new2' },
    { slot: 6, mode: 'fitting', field: 'fittingKind', value: 'textil2' },
  ]
  for (const item of cases) {
    await hold(page)
    await extendTo(page, item.slot)
    await page.keyboard.up('4')
    expect(await page.evaluate(field => [window.__quadroDev.builder.mode, window.__quadroDev.builder[field]], item.field)).toEqual([item.mode, item.value])
  }
  expect(await page.evaluate(() => window.__quadroDev.builder.fittingPart)).toBe('textile_rainbow')
})

test('中心松开进入配置，圆环点选替换、拖拽换位、移除、刷新保持', async ({ page }) => {
  await boot(page)
  await configure(page)
  await expect(page.locator('.cc-mini-ring')).toHaveCount(1)
  await expect(page.locator('.cc-mini-slot')).toHaveCount(7)
  await expect(page.locator('.cc-mini-fixed')).toContainText('取消')
  const first = page.locator('.cc-mini-slot[data-index="0"]')
  const third = page.locator('.cc-mini-slot[data-index="2"]')
  const firstKey = await first.getAttribute('data-key')
  const thirdKey = await third.getAttribute('data-key')
  const start = await first.boundingBox(), end = await third.boundingBox()
  await page.mouse.move(start!.x + start!.width / 2, start!.y + start!.height / 2)
  await page.mouse.down()
  await page.mouse.move(end!.x + end!.width / 2, end!.y + end!.height / 2, { steps: 12 })
  await expect(third).toHaveAttribute('data-drop', 'true')
  await page.mouse.up()
  await expect(first).toHaveAttribute('data-key', thirdKey!)
  await expect(third).toHaveAttribute('data-key', firstKey!)
  await expect(page.locator('.cc-edit-heading')).toHaveCount(0)
  await expect(page.getByLabel('搜索名称或尺寸')).toBeVisible()

  await page.locator('.cc-mini-slot[data-index="1"]').click()
  await expect(page.locator('.cc-search input')).toBeFocused()
  await page.locator('.cc-mini-slot[data-index="2"]').click()
  await expect(page.locator('.cc-edit-heading')).toContainText('位置 3')
  await page.locator('.cc-mini-slot[data-index="1"]').click()
  await expect(page.locator('.cc-edit-heading')).toContainText('位置 2')
  const ringBox = await page.locator('.cc-mini-ring').boundingBox()
  const dialogBox = await page.locator('.qb-components-config').boundingBox()
  expect(ringBox!.y).toBeGreaterThanOrEqual(dialogBox!.y)
  expect(ringBox!.y + ringBox!.height).toBeLessThan(dialogBox!.y + dialogBox!.height)
  await page.getByLabel('搜索名称或尺寸').fill('30*30')
  await page.locator('.cc-catalogue-card[data-choice-key="panel:panel_30x30"]').click()
  await expect(page.locator('.cc-mini-slot[data-index="1"]')).toHaveAttribute('data-key', 'panel:panel_30x30')
  await page.locator('.cc-mini-slot[data-index="6"]').click()
  const addedKey = await page.locator('.cc-catalogue-card:not(:disabled)').first().getAttribute('data-choice-key')
  await page.locator('.cc-catalogue-card:not(:disabled)').first().click()
  await expect(page.locator('.cc-mini-slot[data-index="6"]')).toHaveAttribute('data-key', addedKey!)
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('#canvas-host')).toHaveAttribute('data-ready', 'true')
  await configure(page)
  await expect(page.locator('.cc-mini-slot[data-index="0"]')).toHaveAttribute('data-key', thirdKey!)
  await expect(page.locator('.cc-mini-slot[data-index="1"]')).toHaveAttribute('data-key', 'panel:panel_30x30')
  await expect(page.locator('.cc-mini-slot[data-index="6"]')).toHaveAttribute('data-key', addedKey!)
  await page.locator('.cc-mini-slot[data-index="6"]').click()
  await page.locator('[data-action="remove"]').click()
  await expect(page.locator('.cc-mini-slot[data-index="6"]')).toHaveAttribute('data-empty', 'true')
  for (let n = 6; n > 0; n--) {
    await page.locator('.cc-mini-slot[data-index="0"]').click()
    await page.locator('[data-action="remove"]').click()
    await expect(page.locator('.cc-mini-slot[data-key]:not([data-key=""])')).toHaveCount(n - 1)
  }
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('#canvas-host')).toHaveAttribute('data-ready', 'true')
  await page.mouse.move(760, 450)
  await page.keyboard.press('4')
  await expect(page.locator('.cc-mini-slot[data-key]:not([data-key=""])')).toHaveCount(0)
  await page.getByRole('button', { name: '恢复默认', exact: true }).click()
  await expect(page.locator('.cc-mini-slot[data-key]:not([data-key=""])')).toHaveCount(6)
})

test('搜索直达打开即搜索，回车加入、结果去重和刷新保持', async ({ page }) => {
  await boot(page)
  await configure(page)
  await expect(page.getByLabel('搜索名称或尺寸')).toBeVisible()
  await expect(page.locator('.cc-edit-heading')).toHaveCount(0)
  await page.getByLabel('搜索名称或尺寸').fill('30*30')
  await expect(page.locator('.cc-catalogue-card[data-choice-key="panel:panel_30x30"]')).toContainText('加入')
  await page.getByLabel('搜索名称或尺寸').press('Enter')
  await expect(page.locator('.cc-mini-slot[data-index="6"]')).toHaveAttribute('data-key', 'panel:panel_30x30')
  await expect(page.locator('.cc-catalogue-card[data-choice-key="panel:panel_30x30"]')).toBeDisabled()
  await page.getByLabel('搜索名称或尺寸').press('Enter')
  await expect(page.locator('.cc-mini-slot[data-key]:not([data-key=""])')).toHaveCount(7)
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('#canvas-host')).toHaveAttribute('data-ready', 'true')
  await configure(page)
  await expect(page.locator('.cc-mini-slot[data-index="6"]')).toHaveAttribute('data-key', 'panel:panel_30x30')
})

test('真实选区保存、配置取用、刷新、放置、撤销、删除', async ({ page }) => {
  await boot(page)
  await buildAndSelect(page)
  await saveAndConfigure(page, '窗框 456')
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('#canvas-host')).toHaveAttribute('data-ready', 'true')
  await hold(page)
  await extendTo(page, 7)
  await page.keyboard.up('4')
  expect(await page.evaluate(() => window.__quadroDev.builder.pasting)).toBe(true)
  await page.mouse.move(930, 600)
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('ArrowUp')
  await page.mouse.click(930, 600)
  await expect.poll(() => page.evaluate(() => window.__quadroDev.builder.pasting)).toBe(false)
  await expect.poll(() => page.evaluate(() => window.__quadroDev.model.tubes.size)).toBe(24)
  await page.keyboard.press('ControlOrMeta+z')
  await expect.poll(() => page.evaluate(() => window.__quadroDev.model.tubes.size)).toBe(12)
  await configure(page)
  await page.getByRole('button', { name: '保存选区与管理组件', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '删除', exact: true }).click()
  await page.getByRole('button', { name: '删除组件', exact: true }).click()
  await expect(page.locator('.qb-components-row')).toHaveCount(0)
  await page.getByRole('button', { name: '保存选区与管理组件', exact: true }).click()
  await expect(page.locator('.cc-mini-slot[data-key]:not([data-key=""])')).toHaveCount(6)
})

test('输入不会触发快捷键，Esc/取消/失焦不会改变已有粘贴', async ({ page }) => {
  await boot(page)
  await buildAndSelect(page)
  await configure(page)
  await page.locator('.cc-mini-slot[data-index="0"]').click()
  await page.getByLabel('搜索名称或尺寸').fill('456')
  await page.keyboard.type('4')
  await expect(page.getByLabel('搜索名称或尺寸')).toHaveValue('4564')
  await page.keyboard.press('Escape')
  await page.keyboard.press('ControlOrMeta+c')
  await page.keyboard.press('ControlOrMeta+v')
  await hold(page)
  await extendTo(page, 3)
  await page.keyboard.up('4')
  expect(await page.evaluate(() => window.__quadroDev.builder.pasting)).toBe(true)
  await hold(page)
  await page.keyboard.press('Escape')
  await page.keyboard.up('4')
  expect(await page.evaluate(() => window.__quadroDev.builder.pasting)).toBe(true)
  await hold(page)
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await page.keyboard.up('4')
  await expect(page.locator('[data-ui="custom-components"]')).toHaveCount(0)
  expect(await page.evaluate(() => window.__quadroDev.builder.pasting)).toBe(true)
})

test('组件预览切换新标签不会把旧模型写进新页', async ({ page }) => {
  await boot(page)
  await buildAndSelect(page)
  await saveAndConfigure(page, '立柱')
  await page.keyboard.press('Escape')
  await hold(page)
  await extendTo(page, 7)
  await page.keyboard.up('4')
  expect(await page.evaluate(() => window.__quadroDev.builder.pasting)).toBe(true)
  await page.getByRole('button', { name: '+', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.__quadroDev.builder.pasting)).toBe(false)
  expect(await page.evaluate(() => window.__quadroDev.model.tubes.size)).toBe(0)
  await page.keyboard.press('Escape')
  expect(await page.evaluate(() => window.__quadroDev.model.tubes.size)).toBe(0)
  await page.reload()
  await expect(page.locator('#canvas-host')).toHaveAttribute('data-ready', 'true')
  expect(await page.evaluate(() => window.__quadroDev.model.tubes.size)).toBe(12)
})

test('手机点击入口、分页、边缘定位与配置滚动', async ({ page }) => {
  await boot(page)
  await configure(page)
  for (let n = 7; n <= 9; n++) {
    if (n === 8) await page.locator('.cc-ring-controls').getByRole('button', { name: '后移', exact: true }).click()
    await page.locator(`.cc-mini-slot[data-index="${n - 1}"]`).click()
    await page.locator('.cc-catalogue-card:not(:disabled)').first().click()
    await expect(page.locator('.cc-mini-slot[data-key]:not([data-key=""])')).toHaveCount(n === 7 ? 7 : n - 7)
  }
  await page.keyboard.press('Escape')
  await hold(page)
  await page.mouse.wheel(0, 100)
  await expect(page.locator('.qb-components-pager')).toContainText('2 / 2')
  await extendTo(page, 3)
  await page.keyboard.up('4')
  await page.setViewportSize({ width: 393, height: 852 })
  await page.locator('[data-ui="tool-custom-components"]').click()
  await expect(page.locator('.qb-component-slot')).toHaveCount(8)
  await expect(page.locator('.qb-components-pager')).toContainText('1 / 2')
  const box = await page.locator('[data-ui="custom-components"]').boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(12)
  expect(box!.y + box!.height).toBeLessThanOrEqual(840)
  await page.getByRole('button', { name: '下一组' }).click()
  await expect(page.locator('.qb-components-pager')).toContainText('2 / 2')
  await page.locator('[data-configure]').click()
  await expect(page.locator('.cc-mini-ring')).toBeVisible()
  await page.screenshot({ path: '.work/components-config-mobile-v4.png' })
  await page.setViewportSize({ width: 844, height: 390 })
  await page.locator('.cc-mini-slot[data-index="0"]').click()
  await expect(page.locator('.cc-search input')).toBeFocused()
  const shortRing = await page.locator('.cc-mini-ring').boundingBox()
  const shortDialog = await page.locator('.qb-components-config').boundingBox()
  expect(shortRing!.y).toBeGreaterThanOrEqual(shortDialog!.y)
  expect(shortRing!.y + shortRing!.height).toBeLessThan(shortDialog!.y + shortDialog!.height)
  await page.locator('.cc-mini-slot[data-index="1"]').click()
  await expect(page.locator('.cc-edit-heading')).toContainText('位置 2')
  await page.screenshot({ path: '.work/components-config-landscape-v4.png' })
})
